source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "jekyll-paginate", "~> 1.1"
gem "jekyll-redirect-from", "~> 0.16"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-archives", "~> 2.2"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-feed", "~> 0.17"
gem "jekyll-include-cache", "~> 0.2"

# Chirpy theme
gem "jekyll-theme-chirpy", "~> 7.0"

# GitHub Pages (optional, for compatibility)
# gem "github-pages", group: :jekyll_plugins

